before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update 
  - sudo apt-get install gfortran
  - git clone http://github.com/wellposed/wellposed-travis travis
  - ./travis/scripts/build-openblas.sh
install:
  - sudo apt-get install rust-nightly
script:
    - echo "done"
  # - rustpkg test tests
  # - rustpkg build --opt-level=3 bench
  # -  sh .travis.sh
  
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#numerical-haskell" # yes, its a general math channel sometimes too :) 
    skip_join: true
    template:
      - "\x0313 hOpenBLAS \x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
